### ISSUE TITLE
Great!We want some Sample Project

### ISSUE THREAD

**Issue by androidcn** [Vitaa/IAPurchaseManager#1]
We want some Sample Project

**Comment by androidcn** [comment]
and i want add validation recipt

**Comment by Vitaa** [comment]
Hi!
Sample app'll need real products ids, but iTunes connect deletes unsubmitted apps after 90 days, so it's almost impossible to maintain working sample code.  But it's rather straightforward to use tool, just drag  IAPManager.swift to your project. To make a purchase call purchaseProductWithId method. 
I updated readme file to make it clear.

It'll be great to add validation! I was thinking about validating receipts locally.

**Comment by androidcn** [comment]
thanks
validating receipts locally
just i need
