### ISSUE TITLE
IAPManager.sharedManager.isProductPurchased(productId) sometimes returns false although product is purchased

### ISSUE THREAD

**Issue by haemi** [Vitaa/IAPurchaseManager#12]
I do get reports from users that they have to restore their purchases sometimes because the

IAPManager.sharedManager.isProductPurchased(productId)

method returns false although the product is purchased... what could be the reason for this?

**Comment by haemi** [comment]
seems this happens whenever the app is closed completely.

**Comment by victorcampeanu** [comment]
`func purchasedItemsURL() -> URL {
        let documentsDirectory = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!
        return URL(fileURLWithPath: documentsDirectory).appendingPathComponent("purchased.plist")
    }`

replace URL(string: with URL(fileURLWithPath:

**Comment by Vitaa** [comment]
thanks @victorcampeanu! I fixed this line.
