### ISSUE TITLE
Thank you First

### ISSUE THREAD

**Issue by nsoud** [Vitaa/IAPurchaseManager#4]
Please i have like 5 iD i want to insert them where i can put them so to work for each id

Thank you

**Comment by Vitaa** [comment]
are you asking where to store product ids for your in-app purchases? Well, you can save them in plist or just use static strings in your view controller. It depends on your project.

**Comment by nsoud** [comment]
Thank you very much for your support.

On Mon, Apr 18, 2016 at 11:54 PM, Vitaliya Solomina <
notifications@github.com> wrote:

> are you asking where to store product ids for your in-app purchases? Well,
> you can save them in plist or just use static strings in your view
> controller. It depends on your project.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Vitaa/IAPurchaseManager/issues/4#issuecomment-211570954

## 

_NAYER ABU SOUD,ENG_Multimedia Specialist & Consultant
 ---------------------------------------------Multimedia
Trainer,E-Learning Consultant
Tel: +972 547386627, +970 598948203
Web: FOX-MEDIA.CO http://fox-media.co/
